//
//  FeedDetailInteractor.swift
//  ViperXMLDemo
//
//  Created Gagan Vishal on 2019/08/08.
//  Copyright © 2019 Gagan Vishal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

/*
 Uncomment below codes if you want to call a service for detail page.
*/

import UIKit

class FeedDetailInteractor {
    weak var presenter: FeedDetailPresenterProtocol?
/*    var webRequestHandler: WebViewInputProtocol?                  */
}

//MARK:- FeedDetailInteractorProtocol
extension FeedDetailInteractor : FeedDetailInteractorProtocol {
    func fetchWebRequest(viewModel: FeedViewModel) {
/*        self.webRequestHandler?.requestWebViewContent(viewModel: viewModel)  */
    }
    
    func onSuccess(htmlData: Data) {
/*        presenter?.didLoadString(htmlData: htmlData)              */
    }
    
    func onFailue(error: Error) {
/*        presenter?.didFailed(with: error)             */
    }
}
