//
//  FeedDetailPresenter.swift
//  ViperXMLDemo
//
//  Created Gagan Vishal on 2019/08/08.
//  Copyright © 2019 Gagan Vishal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FeedDetailPresenter {
    weak private var view: FeedDetailViewProtocol?
    var interactor: FeedDetailInteractorProtocol?
    private let router: FeedDetailWireframeProtocol
    let viewModel: FeedViewModel

    init(interface: FeedDetailViewProtocol, interactor: FeedDetailInteractorProtocol?, router: FeedDetailWireframeProtocol, feedModel: FeedViewModel) {
        self.view = interface
        self.interactor = interactor
        self.router = router
        self.viewModel = feedModel
    }
}

//MARK:- FeedDetailPresenterProtocol
extension FeedDetailPresenter: FeedDetailPresenterProtocol {
    
    func viewDidLoaded() {
        view?.showHudView()
        self.view?.webViewStartLoading(with: self.viewModel)
        /*-----------------------Uncommet if want to load data from webresvice request-----------------------*/
        /*       self.interactor?.fetchWebRequest(viewModel: self.viewModel)   */
    }
    
    /*-----------------------Use below if you are trying a call a webservice and want to post on ViewController--------------*/
    func didLoadString(htmlData: Data) {
    }
    
    func didLoadString(htmlString: Data) {  //You can use if you want to load HTML string in WebView
    }
    
    func didFailed(with error: Error) {
        view?.hideHudView()
    }
}
