//
//  FeedDetailProtocols.swift
//  ViperXMLDemo
//
//  Created Gagan Vishal on 2019/08/08.
//  Copyright © 2019 Gagan Vishal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol FeedDetailWireframeProtocol: class {
 //if you want to push on next screen. Add your function here
}

//MARK: Presenter -
protocol FeedDetailPresenterProtocol: class {
    func viewDidLoaded()
    func didLoadString(htmlString: Data)
    func didFailed(with error: Error)
}

//MARK: Interactor -
protocol FeedDetailInteractorProtocol: class {

  var presenter: FeedDetailPresenterProtocol?  { get set }
    
    func fetchWebRequest(viewModel: FeedViewModel)
    
    func onSuccess(htmlData: Data)
    func onFailue(error: Error)
   
}

/*------------------------- Uncomment below code if you want load detail page from server -----------------------*/
/*
protocol WebViewInputProtocol {
    var webRequestHandler: FeedDetailInteractorProtocol? {get set}
    func requestWebViewContent(viewModel: FeedViewModel)
}
*/

//MARK: View - FeedDetailViewProtocol
protocol FeedDetailViewProtocol: class {
    
    var presenter: FeedDetailPresenterProtocol?  { get set }
    
    func webViewStartLoading(with feed: FeedViewModel)
    //use these in service call  if there is.
    func hideHudView()
    func showHudView()
}
