//
//  FeedDetailRouter.swift
//  ViperXMLDemo
//
//  Created Gagan Vishal on 2019/08/08.
//  Copyright © 2019 Gagan Vishal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FeedDetailRouter: FeedDetailWireframeProtocol {
    weak var viewController: UIViewController?
    static func createFeedDetailModule(viewModel: FeedViewModel) -> UIViewController {
        let view = UIStoryboard(name: "Main", bundle: .main).instantiateViewController(withIdentifier: "feedDetail") as! FeedDetailViewController
        let interactor = FeedDetailInteractor()
        let router = FeedDetailRouter()
        let presenter = FeedDetailPresenter(interface: view, interactor: interactor, router: router,feedModel: viewModel)
/*----------------------------Uncomment below if you want to get data from server request----------------------------*/
        /*
        let remoteDataManager = RemoteDataManager()
        interactor.webRequestHandler = remoteDataManager
        remoteDataManager.webRequestHandler = interactor
         */
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        return view
    }
}
